#! /bin/sh

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/local/capi/capid.py
NAME=capid
DESC="Capi daemon"

test -f $DAEMON || exit 0

set -e

case "$1" in
  start)
	echo -n "Starting $DESC: "
	python $DAEMON start
	echo "$NAME."
	;;
  stop)
	echo -n "Stopping $DESC: "
	python $DAEMON stop
	echo "$NAME."
	;;
  restart|force-reload)
	echo -n "Restarting $DESC: "
	python $DAEMON stop
	sleep 1
	python $DAEMON start
	echo "$NAME."
	;;
  *)
	N=/etc/init.d/$NAME
	echo "Usage: $N {start|stop|restart|force-reload}" >&2
	exit 1
	;;
esac
